const apiBase = '/api';
const state = { jobs: [], pendingJobs: null };
const els = {
  jobs: document.getElementById('jobs'), total: document.getElementById('totalJobs'), active: document.getElementById('activeJobs'),
  done: document.getElementById('doneJobs'), failed: document.getElementById('failedJobs'), status: document.getElementById('statusText'),
  settings: document.getElementById('settingsText'), form: document.getElementById('enqueueForm'), url: document.getElementById('urlInput'),
  filename: document.getElementById('filenameInput'), quality: document.getElementById('qualityInput'), paste: document.getElementById('pasteButton'), reload: document.getElementById('reloadButton'),
};
function formatBytes(v){ if(!v) return '—'; const u=['B','KB','MB','GB']; let s=Number(v),i=0; while(s>=1024&&i<u.length-1){s/=1024;i++;} return (s>=10||i===0?s.toFixed(0):s.toFixed(1))+' '+u[i]; }
function formatDate(v){ if(!v) return '—'; const d=new Date(v); return Number.isNaN(d.getTime())?'—':d.toLocaleString(); }
function pct(job){ if(['probing','extracting'].includes(job.status)) return 8; if(job.status==='merging') return 96; if(job.status==='completed') return 100; if(typeof job.progressPercent==='number' && job.progressPercent>0) return Math.max(0, Math.min(100, Math.round(job.progressPercent))); if(job.extractor==='yt-dlp' && job.status==='downloading') return job.downloadedBytes>0 ? 72 : 18; if(!job.totalBytes) return 0; return Math.max(0, Math.min(100, Math.round((job.downloadedBytes/job.totalBytes)*100))); }
function progressLabel(job, progress){ if(typeof job.progressPercent==='number' && job.progressPercent>0) return job.progressText||`${progress}%`; if(job.extractor==='yt-dlp' && job.status==='downloading') return job.downloadedBytes>0 ? 'downloading…' : 'starting…'; if(!job.totalBytes && job.status!=='completed') return '—'; return `${progress}%`; }
function setStatus(text, isError=false){ els.status.textContent=text; els.status.style.color=isError?'#fecaca':''; }
function hasActiveUserSelection(){ const sel = window.getSelection?.(); return !!(sel && !sel.isCollapsed && String(sel).trim()); }
function applyJobs(jobs){ state.jobs = jobs||[]; renderStats(); renderJobs(); }
function flushPendingJobs(){ if(!state.pendingJobs || hasActiveUserSelection()) return; const next = state.pendingJobs; state.pendingJobs = null; applyJobs(next); }
function renderStats(){ const total=state.jobs.length; const active=state.jobs.filter(j=>['queued','planned','probing','extracting','downloading','merging'].includes(j.status)).length; const done=state.jobs.filter(j=>j.status==='completed').length; const failed=state.jobs.filter(j=>['failed','canceled'].includes(j.status)).length; els.total.textContent=total; els.active.textContent=active; els.done.textContent=done; els.failed.textContent=failed; }
function escapeHTML(v){ return String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'); }
function jobButtons(job){ const parts=[]; parts.push(`<button class="secondary" data-action="open" data-job-id="${job.jobId}">Open folder</button>`); if(job.canResume) parts.push(`<button class="secondary" data-action="resume" data-job-id="${job.jobId}">Resume</button>`); if(['queued','planned','probing','extracting','downloading','merging'].includes(job.status)) parts.push(`<button class="secondary" data-action="cancel" data-job-id="${job.jobId}">Cancel</button>`); parts.push(`<button class="danger" data-action="remove" data-job-id="${job.jobId}">Remove</button>`); return parts.join(''); }
function renderJobs(){ if(!state.jobs.length){ els.jobs.innerHTML='<div class="panel small muted">No jobs yet. Send one from Firefox or paste a URL here.</div>'; return; }
els.jobs.innerHTML = state.jobs.map(job=>{ const progress=pct(job); const extractor=job.extractor?`<span class="pill">${escapeHTML(job.extractor)}</span>`:''; const error=job.lastError?`<div class="notice">Last error: ${escapeHTML(job.lastError)}</div>`:''; const sizeLabel=(job.extractor==='yt-dlp' && job.status!=='completed' && !job.totalBytes)?`${formatBytes(job.downloadedBytes)} downloaded`:`${formatBytes(job.downloadedBytes)} / ${formatBytes(job.totalBytes)}`; const liveLabel=progressLabel(job, progress); const transferMeta=[job.speedText, job.etaText?`ETA ${job.etaText}`:''].filter(Boolean).join(' • '); return `<article class="job"><div class="job-top"><div><div class="job-title">${escapeHTML(job.filename||'Unnamed file')}</div><div class="small muted code">${escapeHTML(job.url||'')}</div></div><span class="pill ${escapeHTML(job.status||'queued')}">${escapeHTML(job.status||'queued')}</span></div><div class="progress"><div class="bar" style="width:${progress}%"></div></div><div class="meta"><span>${sizeLabel}</span><span>${liveLabel}</span><span>Created ${escapeHTML(formatDate(job.createdAt))}</span><span>Updated ${escapeHTML(formatDate(job.modifiedAt))}</span></div><div class="meta2"><span>${job.acceptRanges ? 'Range support: Yes' : 'Range support: No'}</span>${extractor}${job.streamKind?`<span class="pill">${escapeHTML(job.streamKind)}</span>`:''}${transferMeta?`<span>${escapeHTML(transferMeta)}</span>`:''}${job.outputPath?`<span class="code">${escapeHTML(job.outputPath)}</span>`:''}</div>${error}<div class="job-actions">${jobButtons(job)}</div></article>`; }).join(''); }
async function loadJobs(){ const res=await fetch(apiBase+'/jobs'); if(!res.ok) throw new Error('Failed to load jobs'); const data=await res.json(); const jobs=data.jobs||[]; if(hasActiveUserSelection()){ state.pendingJobs = jobs; return; } state.pendingJobs = null; applyJobs(jobs); }
async function loadSettings(){ const res=await fetch(apiBase+'/settings'); const data=await res.json(); els.settings.textContent=`Downloads dir: ${data.downloadsDir} • Bridge: ${data.helperName}`; }
async function enqueueJob(event){ event.preventDefault(); const payload={ url: els.url.value.trim(), filename: els.filename.value.trim(), youtubeQuality: els.quality.value }; if(!payload.url){ setStatus('URL is required', true); return; } setStatus('Queueing job…'); const res=await fetch(apiBase+'/jobs',{ method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(payload) }); const data=await res.json(); if(!res.ok || data.ok===false) throw new Error(data.error||data.message||'Failed to queue job'); els.form.reset(); els.quality.value='highest'; setStatus(data.message||'Queued'); await loadJobs(); }
async function handleAction(event){ const button=event.target.closest('button[data-action]'); if(!button) return; const action=button.dataset.action; const jobId=button.dataset.jobId; let method='POST'; if(action==='remove') method='DELETE'; const res=await fetch(`${apiBase}/jobs/${encodeURIComponent(jobId)}/${action}`, { method }); const data=await res.json(); if(!res.ok || data.ok===false) throw new Error(data.error||'Action failed'); setStatus(action+' ok'); await loadJobs(); }
async function boot(){ await Promise.all([loadJobs(), loadSettings()]); setStatus('Downloader app ready'); setInterval(()=>loadJobs().catch(err=>setStatus(err.message,true)), 1500); document.addEventListener('selectionchange', ()=>flushPendingJobs()); window.addEventListener('focus', ()=>flushPendingJobs()); }
els.form.addEventListener('submit', e=>enqueueJob(e).catch(err=>setStatus(err.message,true))); els.jobs.addEventListener('click', e=>handleAction(e).catch(err=>setStatus(err.message,true))); els.reload.addEventListener('click', ()=>window.location.reload()); els.paste.addEventListener('click', ()=>navigator.clipboard?.readText().then(t=>els.url.value=t).catch(()=>{})); boot().catch(err=>setStatus(err.message,true));
